### ISSUE TITLE
Feat:Add Social Media Icons to Footer

### ISSUE THREAD

**Issue by chandannekya** [VanshKing30/FoodiesWeb#288]
### Describe the feature

Currently, our application lacks social media icons in the footer, which limits our users' ability to connect with us on social media platforms. Adding social media icons will enhance the user experience by providing easy access to our social media profiles and encouraging greater engagement

### Add ScreenShots

![Screenshot_2024-06-10-10-05-28-243_com android chrome-edit](https://github.com/VanshKing30/FoodiesWeb/assets/121476456/4f2d1aba-a963-41ca-831b-d24dbda7e166)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by hustlerZzZ** [comment]
We dont have any social media page... so there is no use of adding social media icons

**Comment by chandannekya** [comment]
> We dont have any social media page... so there is no use of adding social media icons

For future updates...?

**Comment by roshnimishraa** [comment]
Hi @chandannekya my solution of this is issue is 
1. We can create a Footer Page component in React and integrate it to our App component so that it is visible to every web page.
In Footer section we can add Connect with Us with Social media links
2. And We can also also users to sign up with their Social Media account to webpage.
