### ISSUE TITLE
Feat:  Add "Forgot Password" Functionality

### ISSUE THREAD

**Issue by Saksham2k3s** [VanshKing30/FoodiesWeb#339]
### Describe the feature

Implement a "Forgot Password" feature to allow users to reset their passwords if they have forgotten them. This feature should include a link on the login page that guides users through the process of resetting their password.

### Add ScreenShots

Implement the Forgot Password Feature

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by hustlerZzZ** [comment]
Kindly, explain how you are going to proceed?

**Comment by ROKUMATE** [comment]
I have an intuition for this question ... 
will use the nodemailer package to send mail to the person have that email with an OTP... 
and will create a page to seek the OTP from the user ... 
If it is right will proceed to the next step of changing the password of the user 

I am a gssoc contributor... 
Do assign me this issue along with the required labels so that I could start working on it

**Comment by hustlerZzZ** [comment]
Ok, go ahead! @ROKUMATE

**Comment by ROKUMATE** [comment]
@hustlerZzZ 
Sir there are many error in the repo while running also 
which are caused by recent 2-5 days pull requests 
<img width="1464" alt="Screenshot 2024-06-30 at 12 53 14 PM" src="https://github.com/VanshKing30/FoodiesWeb/assets/77058883/eb0abaf9-25c6-464b-9d2a-f3ee13a9f336">
<img width="1461" alt="Screenshot 2024-06-30 at 12 53 01 PM" src="https://github.com/VanshKing30/FoodiesWeb/assets/77058883/465bce97-9752-4dc3-a33a-72e8aea3a45d">


There were more in the `components/nav.jsx` file also 
I would recommend create a new issue and merge a pr for solving recent all this errors so it will be easy for others to fork and code
